version: '2'
services:
    kibana:
        build: ./kibana
        ports:
            - "5601:5601"
        networks:
            - inner
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
networks:
    inner:
        external:
            name: docker_inner
