version: '2'
services:
#    web_server:
#        build: ./nginx
#        ports:
#            - "80:80"
#        links:
#            - php-fpm
#        volumes:
#            - /mnt/hgfs/Projects/Docker/my_dockers/lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf
#            - /mnt/hgfs/Projects/Docker/my_dockers/lnmp/nginx/sites:/etc/nginx/conf.d/
#            - /data/log/nginx:/var/log/nginx
#            - /mnt/hgfs/Projects:/www
    mysql_master:
        build: ./mysql
        ports:
            - "3306:3306"
        volumes:
            - /data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: Devroot_123
    redis_6379:
        build: ./redis
        ports:
            - "6379:6379"
    php-fpm:
        build: ./php
        ports:
            - "9000:9000"
        links:
            - mysql_master
            - redis_6379
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini 
            - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf 
            - /mnt/hgfs/Projects:/www
    solr:
        build: ./solr
        ports:
            - "8983:8983"
        links:
            - mysql_master
        volumes:
            - /data/solr/mycores:/opt/solr/server/solr/mycores
        
        
    
        
