version: '2'
services:
    logstash:
        build: ./logstash        
        networks:
            - inner
    elasticsearch:
        build: ./elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - inner
    kibana:
        build: ./kibana
        ports:
            - "5610:5610"
        depends_on:
            - elasticsearch
        networks:
            - inner
networks:
    outter:
    inner:
