version: '2'
services:
    web:
        image: 'twang2218/gitlab-ce-zh:latest'
        restart: always
        hostname: 'gitlab.muxi.org'
        environment:
          GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://gitlab.muxi.org'
            gitlab_rails['gitlab_shell_ssh_port'] = 2224
        ports:
          - '80:80'
          - '443:443'
          - '2224:22'
        volumes:
          - '/data/gitlab/config:/etc/gitlab'
          - '/data/gitlab/logs:/var/log/gitlab'
          - '/data/gitlab/data:/var/opt/gitlab'