version: '2'
services:
    logstash:
        build: ../logstash 
        volumes:
            - ../logstash/conf.d/:/etc/logstash/conf.d/
        depends_on:
            - elasticsearch
        networks:
            - inner
        command: logstash -f /etc/logstash/conf.d/indexer.conf
    elasticsearch:
        build: ./elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - inner
networks:
    inner:
        external:
            name: docker_inner
